name: ros CI build

on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string
      ros_distribution:
        required: true
        type: string
      docker_image:
        required: true
        type: string
      ros_version:
        required: true
        type: number

jobs:
  test_build_docker: # On Linux, iterates on all ROS 1 and ROS 2 distributions.
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker_image }}
    steps:
    - name: setup ROS environment
      uses: LCAS/setup-ros@v0.2
      with:
        required-ros-distributions: ${{ inputs.ros_distribution }}
    - name: build and test ROS 1
      if: ${{ inputs.ros_version == 1 }}
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: ${{ inputs.packages }}
        target-ros1-distro: ${{ inputs.ros_distribution }}
    - name: build and test ROS 2
      if: ${{ inputs.ros_version == 2 }}
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: ${{ inputs.packages }}
        target-ros2-distro: ${{ inputs.ros_distribution }}
